class AgentQNetwork:
    """
    Individual Deep Q-Network for one agent.
    Maps local observation to per-action Q-values.
    Does NOT receive or use any information about other agents during forward pass.
    """
    def __init__(self, obs_dim: int, action_dim: int, hidden_dims: tuple):
        """
        obs_dim: dimensionality of the agent's local observation vector
        action_dim: number of discrete actions available to the agent
        hidden_dims: tuple specifying hidden layer widths
        """
        ...

    def forward(self, obs: Tensor) -> Tensor:
        """
        obs: (batch, obs_dim) — local observations for this agent
        returns: (batch, action_dim) — Q-values for each action
        """
        ...


class HyperNetwork:
    """
    Generates weight/bias parameters for one layer of the mixing network.
    Conditions on joint state to produce state-dependent mixing coefficients.
    """
    def __init__(self, state_dim: int, output_shape: tuple, non_negative: bool):
        """
        state_dim: dimensionality of the joint state used to condition weights
        output_shape: (rows, cols) shape of the weight matrix to produce, or (size,) for bias
        non_negative: if True, apply non-negative activation to output (required for mixing weights)
                      if False, output is unconstrained (appropriate for bias terms)
        """
        ...

    def forward(self, joint_state: Tensor) -> Tensor:
        """
        joint_state: (batch, state_dim)
        returns: (batch, *output_shape) — weight or bias parameters for this batch
        """
        ...


class MixingNetwork:
    """
    Combines per-agent Q-values into a scalar team value Q_tot.
    All mixing weights generated by HyperNetworks conditioned on joint state.
    Monotonicity constraint (non-negative weights) enforced architecturally.
    """
    def __init__(self, num_agents: int, state_dim: int, hidden_dim: int):
        """
        num_agents: number of agents whose Q-values will be combined
        state_dim: dimensionality of joint state for hypernetwork conditioning
        hidden_dim: width of the single hidden layer in the mixing computation
        """
        ...

    def forward(self, agent_q_values: Tensor, joint_state: Tensor) -> Tensor:
        """
        Computes Q_tot via two-layer mixing with state-conditioned weights.

        agent_q_values: (batch, num_agents) — Q-value for action taken by each agent
        joint_state: (batch, state_dim) — centralized state for hypernetwork conditioning
        returns: (batch,) — scalar Q_tot per sample

        Layer 1: h = activation(batched_matmul(W1, q_values) + b1)
                 W1 shape: (batch, hidden_dim, num_agents), generated by HyperNet + non-neg activation
                 b1 shape: (batch, hidden_dim), generated by HyperNet, unconstrained
        Layer 2: Q_tot = batched_matmul(W2, h) + b2
                 W2 shape: (batch, 1, hidden_dim), generated by HyperNet + non-neg activation
                 b2 shape: (batch, 1), generated by HyperNet, unconstrained

        Monotonicity guarantee: W1 >= 0 and W2 >= 0 by construction => dQ_tot/dQ_i > 0 for all i
        """
        ...


class ReplayBuffer:
    """
    Fixed-capacity circular buffer storing environment transitions.
    Enables off-policy training by decoupling data collection from optimization.
    """
    def __init__(self, capacity: int, transition_schema: dict):
        """
        capacity: maximum number of transitions to store
        transition_schema: dict specifying shapes of each field (obs_i, action_i, reward, done, etc.)
        """
        ...

    def push(self, transition: dict) -> None:
        """Store one environment transition. Overwrites oldest entry when full."""
        ...

    def sample(self, batch_size: int) -> dict:
        """
        Uniform random sample without replacement.
        Returns batch of transitions as dict of tensors.
        """
        ...


class QMIXTrainer:
    """
    Orchestrates the full CTDE training loop.
    Manages: environment interaction, ε-greedy exploration, replay buffer,
    mini-batch sampling, joint loss computation, and target network updates.
    """
    def __init__(
        self,
        env,
        agent_networks: list[AgentQNetwork],
        target_agent_networks: list[AgentQNetwork],
        mixing_network: MixingNetwork,
        target_mixing_network: MixingNetwork,
        replay_buffer: ReplayBuffer,
        config: TrainingConfig,
    ):
        ...

    def select_actions(self, observations: list[Tensor], epsilon: float) -> list[int]:
        """
        ε-greedy action selection for all agents simultaneously.
        With probability ε: uniform random action (exploration)
        With probability 1-ε: greedy argmax on individual agent Q-network (exploitation)

        observations: one observation tensor per agent
        epsilon: current exploration probability
        returns: one discrete action index per agent
        Note: no communication between agents — each acts on its own observation only
        """
        ...

    def compute_loss(self, batch: dict) -> Tensor:
        """
        Computes joint QMIX TD loss over a mini-batch.

        Step 1: Forward pass online agent networks -> current Q-values for actions taken
        Step 2: Forward pass online mixing network -> current Q_tot
        Step 3: Forward pass target agent networks -> Q-values for all next actions
        Step 4: Greedy argmax per agent on target networks -> best next actions (decentralized)
        Step 5: Forward pass target mixing network with best-action Q-values -> target Q_tot
        Step 6: Compute Bellman target: r + gamma * target_Q_tot * (1 - done)
        Step 7: Smooth L1 loss between current Q_tot and Bellman target

        batch: dict with obs_i, action_i, reward, next_obs_i, done, joint_state, next_joint_state
        returns: scalar loss tensor
        """
        ...

    def soft_update_targets(self) -> None:
        """
        Polyak averaging: target_params = tau * online_params + (1-tau) * target_params
        Applied to all agent target networks and target mixing network.
        """
        ...

    def training_step(self, episode: int) -> dict:
        """
        One complete training episode:
        1. Reset environment, get initial observations
        2. Step through environment: select actions, collect transitions, store in buffer
        3. If buffer has enough samples: sample mini-batch, compute loss, gradient step
        4. Soft update target networks
        5. Decay epsilon
        Returns: dict with episode metrics (soups delivered, loss, epsilon, etc.)
        """
        ...

    def evaluate(self, num_episodes: int) -> dict:
        """
        Deterministic evaluation with epsilon=0.
        Each agent selects greedy argmax on its own Q-network only (decentralized execution).
        No mixing network needed during evaluation — only individual agent Q-networks.
        Returns: dict with mean/std soups delivered, per-agent action statistics
        """
        ...